### ISSUE TITLE
Thieves Dent Location Markers

### ISSUE THREAD

**Issue by hoshie** [gamestrafe/thedivision2#2]
Hi,

i failed at setting up the vagrant VM so i had to open an issue : (

But i really appreciate the work you've put into the map.

**Contribution**

I would like to contribute several "Thieves' Dent" Locations which become available once you've gone rogue in the DZ an "triangulated" (location process) the special save house "Thieve's dent" where you can find loot and a special vendor.

**Icon**

The Icon on the map is the same as the DZ Entry/Exit Icon instead of purple the door is white.

**Markers**

I have also screenshots if needed.

1) 41.672911819602085, 199.07226562500003
2) [14.136575651477944, 236.16210937500003] (There's an house on the TD2 map but not on the flar map you're using just FYI)
3) [-12.747516274952714, 246.90673828125003] (Marker Text: In the parking garage)
4) [23.0999442125314, 216.47460937500003]

I've used the debug function to get the coordinates for your map :)

There are more locations - the system each time picks 3 random locations once you reach 100% triangulation status in the DZ.

**Uplay/DZ Crates**

I also got all DZ Crate locations in DZ1 from the beta if you're interested.

You can also add me on UPlay - i would also like to contribute once the game is out - and maybe you can help me with the vagrant i think there might be something wrong with the vagrantfile config.

My Uplay User: "hoshie." (dot at the end is intended)

Additional Video: https://www.youtube.com/watch?v=4AOG892g4wg#t=6m30s

**Comment by ChristianRiesen** [comment]
Thank you very much for your contribution. I wasn't able to test that part in the beta. I do have a few crates on the map now, maybe check and see if it matches yours. They are still standard blue markers, haven';t figured out what Icon I should use for those.

I'll add the markers for thieves den tomorrow, if you find more, please let me know.
