### ISSUE TITLE
Missing DZ Crate + DZ Gate (DZ01)

### ISSUE THREAD

**Issue by hoshie** [gamestrafe/thedivision2#4]
Hey,

i've seen you added more DZ Crates so i'll just post the missing one.

[-2.152813583128846, 213.88183593750003] => Underground car park

Also the DZ gate could be added:

[-27.215556209029675, 191.68945312500003]

Icon: https://imgur.com/a/sGif6d6

**Comment by ChristianRiesen** [comment]
Thank you for your contribution. Added the crate (still adding some more, so it wont show up by the time of this comment). I'm not sure the gate adds much at this point, maybe it becomes actually a useful thing when the invaded DZ's are a thing. I'll keep it in mind though.
