### ISSUE TITLE
Suggestion: Change icon drop shadow

### ISSUE THREAD

**Issue by deuspingu** [gamestrafe/thedivision2#6]
The icon drop shadow is hugely overstated and visually oppressive when viewing multiple markers. Change icon drop shadow drop-shadow(3px 3px 4px #333), this is creates a nice amount of "pop" on the marker, but is cleaner and less overstated.

**Comment by deuspingu** [comment]
Original:

https://cdn.discordapp.com/attachments/534305660335161345/557732287672745994/unknown.png

Muted:

https://cdn.discordapp.com/attachments/534305660335161345/557732345340231680/unknown.png

**Comment by ChristianRiesen** [comment]
Thank you! Excellent suggestion. I changed it on my local copy and it looks great. I have a couple other small things to fix, so it will get deployed with all of them together later today.

**Comment by ChristianRiesen** [comment]
Changed and it's deploying now, thank you @deuspingu 

If you have more inputs, please let me know or just open merge requests :)
