### ISSUE TITLE
New Airdrop box location found.

### ISSUE THREAD

**Issue by TeaCrab** [gamestrafe/thedivision2#7]
A new location of collectible and an airdrop loot box is found.

Proof and how to get up there:
https://imgur.com/a/HLuEILc

**Comment by ChristianRiesen** [comment]
Thank you for the report. I haven't gone through that area in detail yet, but I'll go and place that marker tonight.

Also: Awesome art you have there, stunning.

**Comment by ChristianRiesen** [comment]
Added it, it's deploying at this very moment, thank you @TeaCrab
